/**
 * The modelled engine, what is certificated about it, and what the model makes.
 *
 * Published figures are transcribed from `crates/engine-model/src/published.rs`,
 * which holds them separately from the parameter file the model runs on and
 * carries the tests that keep the two in step. Modelled figures come from
 * `docs/model_validation.md`, regenerated by `just validate`.
 *
 * Power is carried in kW because the nameplate hp is ambiguous and the ambiguity
 * flatters us: 132 kW is 179.5 metric PS but 177.0 mechanical hp, so a "180 hp"
 * label can be made to look exact against either. The certificate states kW.
 */

export interface Comparison {
  quantity: string;
  published: string;
  modelled: string;
  /** Signed, as a percentage of the published figure. Empty where not applicable. */
  delta: string;
  note: string;
}

export const IDENTITY = {
  name: "Austro Engine E4P (AE330)",
  summary:
    "1991 cm3, four cylinders in line. Common-rail direct injection, wastegated fixed-geometry turbocharger, intercooled, full authority digital engine control, 1:1.69 reduction gearbox. It burns heavy fuel, which is why it exists on a military airframe at all.",
  certificate: "EASA TCDS E.200",
  certificateHref: "https://www.easa.europa.eu/en/downloads/7617/en",
  airframe:
    "TAPAS BH-201 flies it. Early prototypes flew NPO-Saturn 36MT turboprops and a Rotax 914. From prototype AF-5 the airframe has twin 180 hp Austro E4P units, and Archer-NG inherits them.",
  block: "Mercedes-Benz OM640",
  hours: "5.5 million flight hours on the E4 series",
};

/**
 * Rating point and envelope, published against modelled.
 *
 * The rating point is the only place both numbers exist, which is the point: it
 * is the single measurement this model can be held to, and everything else in
 * the parameter file was fitted to land on it.
 */
export const RATING: Comparison[] = [
  {
    quantity: "Take-off power",
    published: "132.0 kW",
    modelled: "134.2 kW",
    delta: "+1.7%",
    note: "At 3880 crank rpm. The model runs at full fuelling command. Nothing trims it to the certificate.",
  },
  {
    quantity: "Propeller shaft torque",
    published: "550 N.m",
    modelled: "557 N.m",
    delta: "+1.3%",
    note: "The limit the certificate states. Crank torque follows from it through the 1.69 gearbox.",
  },
  {
    quantity: "Fuel at 100% power",
    published: "39.0 L/h",
    modelled: "39.3 L/h",
    delta: "+0.8%",
    note: "Reproduced simultaneously with power and torque, from a fit to this point alone.",
  },
  {
    quantity: "Critical altitude",
    published: "11,000 ft",
    modelled: "11,000 ft",
    delta: "",
    note: "Where rated power stops being held. No parameter sets it. It falls where compressor sizing meets the shaft speed limit.",
  },
  {
    quantity: "Turbocharger speed",
    published: "178,000 rpm contained",
    modelled: "169,722 rpm at 11,000 ft",
    delta: "4.6% margin",
    note: "Demonstrated containment is what the rotor survives once. It is not an operating limit, so the supervisor holds 169,000 rpm. The power plateau ends when the shaft reaches that speed.",
  },
  {
    quantity: "Maximum overspeed",
    published: "4220 rpm",
    modelled: "governed at 3880",
    delta: "",
    note: "Crank speed. The propeller is constant speed, so the governor holds it and nothing approaches the limit.",
  },
];

/** Certificated limits, for the E4P specifically. The E4 is more permissive. */
export const REDLINES: Comparison[] = [
  {
    quantity: "Oil temperature",
    published: "412.15 K / 139 C",
    modelled: "monitored",
    delta: "",
    note: "TCDS E.200 section IV. The E4 allows 140 C. Quoting that figure here would be the wrong variant.",
  },
  {
    quantity: "Oil pressure",
    published: "2.5 to 6.5 bar",
    modelled: "monitored",
    delta: "",
    note: "The minimum applies at maximum continuous power. Nothing monitors the idle minimum, because the twin never runs the engine at idle.",
  },
  {
    quantity: "Coolant temperature",
    published: "373.15 K / 100 C",
    modelled: "monitored",
    delta: "",
    note: "TCDS E.200 section IV. The E4 allows 105 C.",
  },
  {
    quantity: "Exhaust gas temperature",
    published: "not published",
    modelled: "1123.15 K / 850 C",
    delta: "",
    note: "Estimated. The EECU fuelling limiter holds it and no pilot ever sees it, so no certificated number exists to cite. 850 C is the top of the band a turbo diesel runs at.",
  },
  {
    quantity: "Cylinder head temperature",
    published: "not published",
    modelled: "523.15 K / 250 C",
    delta: "",
    note: "Estimated. Austro's Operation Manual limits oil, coolant, fuel and speed. Its emergency procedures have no CHT case and the DA42 G1000 does not display one. The bound comes instead from measured head metal, which reaches 558 K at the exhaust valve bridge.",
  },
];

/**
 * Why this engine, and what it takes to point the twin at the indigenous one.
 *
 * The honest form of the portability claim. Every engine-specific number is in
 * one TOML file that `EngineParams::from_toml` reads, so a different engine of
 * this class is a parameter file and not a code change. What it is not is a
 * validated model of that engine, and it cannot become one until that engine
 * publishes something to validate against.
 */
export const PORTABILITY = {
  built: [
    [
      "Public rating point",
      "A type certificate, a published take-off rating, a torque limit, a fuel consumption figure and an operating envelope. You can check every claim this model makes against a document you can download.",
    ],
    [
      "Flying on the target airframe",
      "TAPAS BH-201 flies twin E4P units from prototype AF-5. The envelope this model is swept over is therefore one the engine is flown in, including 18 h demonstrated at 28,000 ft.",
    ],
    [
      "A block with a literature",
      "The OM640 gives bore, stroke and compression ratio. The mean value diesel literature is written about engines of this size and architecture.",
    ],
  ] as [string, string][],
  target: [
    [
      "Same class, different displacement",
      "The VRDE and Jayem Automotives 180 hp indigenous engine is a four-cylinder turbocharged heavy-fuel compression-ignition engine at the same rating. Jayem describe a 2.2 litre platform against the E4P's 1991 cm3, so it is a sibling and not a licence build.",
    ],
    [
      "The port is a parameter file",
      "`EngineParams::from_toml` is public and the shipped file is compiled in rather than special-cased. A second engine is therefore a second TOML file. The model class, the filter, the residual generator, the detectors and every screen stay as they are.",
    ],
    [
      "What it would need",
      "A rating point to fit to, and an envelope to sweep. Five numbers are published about the indigenous engine and none of them is a curve, a bore, a stroke or a map. The twin can be pointed at that engine today; it cannot be validated against it. That is a data release, not an engineering problem.",
    ],
  ] as [string, string][],
};
