//! The structured residual matrix: which fault would produce the pattern observed.
//!
//! Health indices report what the filter *spent*, which is not what happened, and
//! three of the four faults in the library land on the wrong index for that reason.
//! What separates them is the **pattern** across channels. Gertler's structured
//! residuals and the fault signature matrix of Frisk, Krysander and Eriksson: each
//! fault is a direction in normalised residual space, and isolation decides which
//! direction the observation lies along.
//!
//! Every column is **generated by running the model**, never authored, and
//! `just signatures` regenerates the printed matrix from this same code.

use engine_model::{EngineParams, Inputs, State, atmosphere, control, integrator};
use serde::Serialize;

use crate::channels::{CHANNELS, TABLE, index as ch};
use crate::indices::index as sub;

/// How many hypotheses are carried.
pub const HYPOTHESES: usize = 9;

/// Index of the no-fault hypothesis. First so that a reader of the matrix meets
/// the null before the alternatives.
pub const NOMINAL: usize = 0;

/// Simulated seconds a perturbed engine is run before its signature is read.
///
/// The oil node is the slow one at minutes, not the gas path at under a second, and
/// a signature read before oil temperature has settled records a transient rather
/// than a fault. Convergence is tested rather than assumed; this is only the cap.
const SETTLE_MAX_S: f64 = 600.0;

/// Penalty a fault hypothesis pays for its free severity, in log likelihood.
///
/// Every fault hypothesis fits the observation better than the null does, because
/// it has an amplitude to spend and the null does not, so an unpenalised comparison
/// diagnoses a fault on a healthy engine every time. Half the 95% point of a
/// chi-square on one degree of freedom, which is the likelihood-ratio test for that
/// one extra parameter: a fault has to beat the null at 95% before it is preferred.
const SEVERITY_PENALTY: f64 = 1.921;

/// One fault hypothesis.
#[derive(Clone, Copy, Debug, Serialize)]
pub struct Hypothesis {
    /// Name, as it appears on a matrix row.
    pub name: &'static str,
    /// Subsystem this fault belongs to, indexing [`crate::indices::NAMES`].
    pub subsystem: usize,
    /// Whether the fault is in the engine or in the instrument watching it.
    ///
    /// Not decoration: a drifting probe is the one hypothesis where the correct
    /// action is to distrust the measurement rather than the machine, and an
    /// operator sent to open an engine that is healthy has been failed badly.
    pub instrument: bool,
}

/// Where a fault acts, and how hard it is pushed to read its direction off.
///
/// Severity only has to be large enough to clear the noise and small enough to stay
/// in the region where the response is roughly linear, because the signature is
/// normalised to a direction and the magnitude is discarded. These are the severities
/// `dragonfly_sim::fault` uses where a matching fault exists there.
enum Perturbation {
    /// No fault. The null hypothesis has no direction.
    None,
    /// Scale one cylinder's injector delivery.
    Injector(usize, f64),
    /// Scale one cylinder's combustion efficiency.
    Combustion(usize, f64),
    /// Scale radiator effectiveness.
    Radiator(f64),
    /// Scale compressor peak efficiency.
    Compressor(f64),
    /// Scale turbine peak efficiency.
    Turbine(f64),
    /// Scale the oil circuit's pressure coefficient.
    OilSupply(f64),
    /// Scale peak volumetric efficiency.
    Volumetric(f64),
    /// Offset one exhaust thermocouple, K. An instrument fault, not an engine one:
    /// the engine is untouched and only the reading moves.
    ExhaustProbe(usize, f64),
}

/// The hypotheses, in matrix row order.
///
/// Nine, covering every health parameter the filter carries plus the two faults
/// that have no parameter at all. Coking and misfire are both present and both on
/// cylinder 3 deliberately: they are the pair that moves every per-cylinder channel
/// identically, and a matrix that cannot be shown separating them is not worth
/// drawing.
const CATALOGUE: [(Hypothesis, Perturbation); HYPOTHESES] = [
    (
        Hypothesis {
            name: "NOMINAL",
            subsystem: sub::COMBUSTION,
            instrument: false,
        },
        Perturbation::None,
    ),
    (
        Hypothesis {
            name: "INJECTOR 3 COKING",
            subsystem: sub::FUEL,
            instrument: false,
        },
        Perturbation::Injector(2, 0.84),
    ),
    (
        Hypothesis {
            name: "CYLINDER 3 MISFIRE",
            subsystem: sub::COMBUSTION,
            instrument: false,
        },
        Perturbation::Combustion(2, 0.80),
    ),
    (
        Hypothesis {
            name: "EGT 3 SENSOR DRIFT",
            subsystem: sub::COMBUSTION,
            instrument: true,
        },
        Perturbation::ExhaustProbe(2, 40.0),
    ),
    (
        Hypothesis {
            name: "RADIATOR FOULING",
            subsystem: sub::THERMAL,
            instrument: false,
        },
        Perturbation::Radiator(0.83),
    ),
    (
        Hypothesis {
            name: "COMPRESSOR EROSION",
            subsystem: sub::AIR_PATH,
            instrument: false,
        },
        Perturbation::Compressor(0.90),
    ),
    (
        Hypothesis {
            name: "TURBINE EROSION",
            subsystem: sub::AIR_PATH,
            instrument: false,
        },
        Perturbation::Turbine(0.90),
    ),
    (
        Hypothesis {
            name: "OIL SUPPLY LOSS",
            subsystem: sub::LUBRICATION,
            instrument: false,
        },
        Perturbation::OilSupply(0.80),
    ),
    (
        Hypothesis {
            name: "INTAKE RESTRICTION",
            subsystem: sub::AIR_PATH,
            instrument: false,
        },
        Perturbation::Volumetric(0.90),
    ),
];

/// The generated matrix, and the isolation that reads it.
#[derive(Clone, Debug)]
pub struct Signatures {
    rows: [[f64; CHANNELS]; HYPOTHESES],
}

/// What the matrix concluded about one observation.
#[derive(Clone, Copy, Debug, Serialize)]
pub struct Diagnosis {
    /// Posterior probability of each hypothesis, summing to one.
    pub posterior: [f64; HYPOTHESES],
    /// Cosine of the angle between the observation and each signature, minus one
    /// to one. This is the match score a matrix row is sorted by, and it is
    /// independent of how severe the fault is.
    pub match_score: [f64; HYPOTHESES],
    /// Index of the most probable hypothesis.
    pub best: usize,
    /// Why each runner-up was rejected, in the words a row label needs.
    pub rejection: [&'static str; HYPOTHESES],
}

impl Signatures {
    /// Generate the matrix by running the model once per hypothesis.
    ///
    /// One settled model run per row, done at construction rather than cached to
    /// disk: a matrix loaded from a file can disagree with the engine parameters
    /// beside it, and this one cannot.
    ///
    /// The reference point is the canonical cruise condition, and signatures shift
    /// with operating point, most of all the thermal ones. Regenerating per operating
    /// point is the honest improvement and is not built.
    #[must_use]
    pub fn generate(params: &EngineParams) -> Self {
        let base = settle(params);
        let rows = std::array::from_fn(|h| {
            let mut z = [0.0; CHANNELS];
            match CATALOGUE[h].1 {
                Perturbation::None => return z,
                Perturbation::ExhaustProbe(cyl, offset_k) => {
                    // The engine is healthy, so the direction is one channel.
                    z[ch::EGT + cyl] = offset_k / TABLE[ch::EGT + cyl].sigma();
                    return unit(z);
                }
                ref p => {
                    let faulted = settle(&perturbed(params, p));
                    for i in 0..CHANNELS {
                        z[i] = (faulted[i] - base[i]) / TABLE[i].sigma();
                    }
                }
            }
            unit(z)
        });
        Self { rows }
    }

    /// The signature of one hypothesis, as a unit vector in normalised residuals.
    #[must_use]
    pub fn row(&self, hypothesis: usize) -> &[f64; CHANNELS] {
        &self.rows[hypothesis]
    }

    /// Which hypothesis explains this residual.
    ///
    /// `detected` gates the comparison and has to: isolation asks *which* fault and
    /// never *whether*, so against a healthy engine it returns whichever hypothesis
    /// best fits the noise.
    ///
    /// A generalised likelihood ratio with severity as a nuisance parameter. Under
    /// hypothesis `h` the residual is `a` times the signature plus unit noise;
    /// maximising over positive `a` gives the projection, and the log likelihood is
    /// half its square less the free parameter's penalty.
    #[must_use]
    pub fn diagnose(&self, normalised: &[f64; CHANNELS], detected: bool) -> Diagnosis {
        let mut match_score = [0.0; HYPOTHESES];
        let mut log_likelihood = [0.0; HYPOTHESES];
        let mut severity = [0.0; HYPOTHESES];
        let magnitude = norm(normalised);

        for (h, row) in self.rows.iter().enumerate() {
            if h == NOMINAL {
                continue;
            }
            let projection: f64 = normalised.iter().zip(row).map(|(z, r)| z * r).sum();
            severity[h] = projection.max(0.0);
            match_score[h] = if magnitude > 0.0 {
                projection / magnitude
            } else {
                0.0
            };
            // A fault that would push a channel the other way does not explain an
            // observation pointing this way, so a negative projection is no
            // evidence at all rather than evidence of a negative severity.
            log_likelihood[h] = 0.5 * projection.max(0.0).powi(2) - SEVERITY_PENALTY;
        }

        let posterior = if detected {
            softmax(&log_likelihood)
        } else {
            let mut p = [0.0; HYPOTHESES];
            p[NOMINAL] = 1.0;
            p
        };

        let best = (0..HYPOTHESES)
            .max_by(|a, b| posterior[*a].total_cmp(&posterior[*b]))
            .unwrap_or(NOMINAL);

        Diagnosis {
            posterior,
            match_score,
            best,
            rejection: std::array::from_fn(|h| self.reject(h, best, severity[h], normalised)),
        }
    }

    /// Why a hypothesis is not the answer, in one channel.
    ///
    /// The channel where this hypothesis's own best fit disagrees most with the
    /// observation: it predicted a residual there and the engine did something else.
    /// `design.md` quotes this on the screen ("rejected: fuel-flow residual is
    /// nominal"), so it has to be about the loser rather than about the winner. The
    /// two are not the same question and only this one is symmetric: coking and
    /// misfire reject each other on **fuel flow** whichever is present.
    fn reject(&self, h: usize, best: usize, severity: f64, z: &[f64; CHANNELS]) -> &'static str {
        if h == best || h == NOMINAL {
            return "";
        }
        self.rows[h]
            .iter()
            .zip(z)
            .enumerate()
            .max_by(|(_, (r, o)), (_, (r2, o2))| {
                (severity * *r - *o)
                    .abs()
                    .total_cmp(&(severity * *r2 - *o2).abs())
            })
            .map_or("", |(i, _)| TABLE[i].name)
    }
}

/// The channel vector a settled engine produces.
///
/// Steady state, so the instrument lags in `crate::nominal` are irrelevant: a first
/// order lag on a constant is that constant. Cylinder metal temperature comes from
/// the settled state for the same reason.
fn settle(p: &EngineParams) -> [f64; CHANNELS] {
    // The canonical cruise point: 3720 rpm at 22,400 ft on a standard day, which is
    // the condition `crate::channels::TABLE` quotes its reference magnitudes at.
    const ALT_M: f64 = 6828.0;
    const RPM: f64 = 3720.0;
    const IAS_M_S: f64 = 40.1;
    const FUEL_CMD: f64 = 0.38;

    let amb = atmosphere::isa(ALT_M);
    let rho = amb.p / (p.gas.r_air * amb.t);
    let tas = IAS_M_S * (atmosphere::isa(0.0).rho / rho).sqrt();

    let mut x = State::at_rest(amb.p, RPM);
    let mut boost = control::BoostController::new();
    let mut u = Inputs {
        fuel_cmd: FUEL_CMD,
        wastegate: 1.0,
        p_amb: amb.p,
        t_amb: amb.t,
        tas_m_s: tas,
        load_torque: 0.0,
    };

    let steps = (SETTLE_MAX_S / integrator::DT) as u32;
    let mut previous = x;
    for i in 0..steps {
        u.wastegate = boost.update(p, u.fuel_cmd, x.p_im, x.omega_tc, integrator::DT);
        u.load_torque = engine_model::evaluate(p, &x, &u).torque_brake;
        x = engine_model::step(p, &x, &u, integrator::DT);
        if i % 200 == 199 {
            let moved = (x.p_im - previous.p_im).abs() / x.p_im
                + (x.t_coolant - previous.t_coolant).abs() / x.t_coolant
                + (x.t_oil - previous.t_oil).abs() / x.t_oil;
            if moved < 1e-9 {
                break;
            }
            previous = x;
        }
    }

    let o = engine_model::evaluate(p, &x, &u);
    let mut z = [0.0; CHANNELS];
    z[ch::RPM] = x.rpm();
    z[ch::MAP] = x.p_im;
    z[ch::MAT] = o.t_intake;
    z[ch::MAF] = o.w_air;
    z[ch::TURBO] = x.turbo_rpm();
    z[ch::TORQUE] = o.torque_brake;
    z[ch::FUEL_FLOW] = o.w_fuel * 3600.0;
    z[ch::OIL_PRESSURE] = o.p_oil;
    z[ch::OIL_TEMPERATURE] = x.t_oil;
    z[ch::COOLANT] = x.t_coolant;
    const N: usize = engine_model::CYLINDERS;
    z[ch::EGT..ch::EGT + N].copy_from_slice(&o.t_egt);
    z[ch::CHT..ch::CHT + N].copy_from_slice(&x.t_cht);
    z[ch::LAMBDA..ch::LAMBDA + N].copy_from_slice(&o.lambda_cylinder);
    z
}

/// The engine with one hypothesis's fault present.
fn perturbed(base: &EngineParams, p: &Perturbation) -> EngineParams {
    let mut e = base.clone();
    match *p {
        Perturbation::None | Perturbation::ExhaustProbe(..) => {}
        Perturbation::Injector(c, s) => e.cylinder.injector_scale[c] *= s,
        Perturbation::Combustion(c, s) => e.cylinder.combustion_efficiency[c] *= s,
        Perturbation::Radiator(s) => e.cooling.radiator_effectiveness *= s,
        Perturbation::Compressor(s) => e.compressor.eta_max *= s,
        Perturbation::Turbine(s) => e.turbine.eta_max *= s,
        Perturbation::OilSupply(s) => e.oil.pressure_coefficient *= s,
        Perturbation::Volumetric(s) => e.cylinder.eta_vol_max *= s,
    }
    e
}

/// Euclidean length.
fn norm(v: &[f64; CHANNELS]) -> f64 {
    v.iter().map(|x| x * x).sum::<f64>().sqrt()
}

/// The same direction, unit length. A zero vector stays zero rather than becoming
/// a division by zero wearing a unit vector's clothes.
fn unit(mut v: [f64; CHANNELS]) -> [f64; CHANNELS] {
    let n = norm(&v);
    if n > 0.0 {
        for x in &mut v {
            *x /= n;
        }
    }
    v
}

/// Normalised exponential of log likelihoods, shifted so the largest is zero.
///
/// The shift is not cosmetic: a well-separated diagnosis puts a log likelihood in
/// the hundreds, and `exp` of that is an infinity that turns the whole posterior
/// into `NaN` at exactly the moment the answer was most certain.
fn softmax(log_likelihood: &[f64; HYPOTHESES]) -> [f64; HYPOTHESES] {
    let max = log_likelihood
        .iter()
        .copied()
        .fold(f64::NEG_INFINITY, f64::max);
    let mut out = [0.0; HYPOTHESES];
    let mut total = 0.0;
    for h in 0..HYPOTHESES {
        out[h] = (log_likelihood[h] - max).exp();
        total += out[h];
    }
    if total > 0.0 {
        for x in &mut out {
            *x /= total;
        }
    }
    out
}

/// The hypothesis descriptions, for a display.
#[must_use]
pub fn catalogue() -> [Hypothesis; HYPOTHESES] {
    std::array::from_fn(|h| CATALOGUE[h].0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use engine_model::engines;

    fn built() -> Signatures {
        Signatures::generate(&engines::ae330())
    }

    fn index_of(name: &str) -> usize {
        catalogue()
            .iter()
            .position(|h| h.name == name)
            .expect("hypothesis is in the catalogue")
    }

    /// An observation manufactured from a signature, at a stated severity.
    fn along(s: &Signatures, h: usize, sigmas: f64) -> [f64; CHANNELS] {
        std::array::from_fn(|i| s.rows[h][i] * sigmas)
    }

    #[test]
    fn every_fault_hypothesis_has_a_direction_and_the_null_has_none() {
        let s = built();
        assert!(norm(s.row(NOMINAL)) < 1e-12);
        for (h, entry) in CATALOGUE.iter().enumerate() {
            if h == NOMINAL {
                continue;
            }
            assert!(
                (norm(s.row(h)) - 1.0).abs() < 1e-9,
                "{}: {}",
                entry.0.name,
                norm(s.row(h))
            );
        }
    }

    /// The physics, read straight off the generated matrix. A restricted nozzle
    /// delivers less fuel, so on an engine running far lean of any temperature peak
    /// that cylinder runs cooler and leaner while its neighbours do not move. This
    /// is the sign that was wrong in an early revision of `design.md`.
    #[test]
    fn coking_runs_its_own_cylinder_cool_and_lean_and_leaves_the_others_alone() {
        let s = built();
        let row = s.row(index_of("INJECTOR 3 COKING"));
        assert!(row[ch::EGT + 2] < -0.1, "EGT 3 {}", row[ch::EGT + 2]);
        assert!(
            row[ch::LAMBDA + 2] > 0.1,
            "lambda 3 {}",
            row[ch::LAMBDA + 2]
        );
        assert!(row[ch::CHT + 2] < 0.0, "CHT 3 {}", row[ch::CHT + 2]);
        assert!(row[ch::TORQUE] < 0.0, "torque {}", row[ch::TORQUE]);
        for i in [0, 1, 3] {
            assert!(
                row[ch::EGT + i].abs() < row[ch::EGT + 2].abs() * 0.2,
                "cylinder {i} moved with cylinder 3"
            );
        }
    }

    /// The one channel that separates the pair, and the reason `crate::health`
    /// refuses to carry a combustion efficiency parameter. Fuel a nozzle never
    /// passes never leaves the tank; fuel injected and not burnt does.
    #[test]
    fn coking_and_misfire_differ_on_fuel_flow_and_almost_nowhere_else() {
        let s = built();
        let coking = s.row(index_of("INJECTOR 3 COKING"));
        let misfire = s.row(index_of("CYLINDER 3 MISFIRE"));

        assert!(
            coking[ch::FUEL_FLOW] < -0.05,
            "coking {}",
            coking[ch::FUEL_FLOW]
        );
        assert!(
            misfire[ch::FUEL_FLOW].abs() < 0.02,
            "misfire {}",
            misfire[ch::FUEL_FLOW]
        );

        // Everywhere else they point the same way, which is exactly why an index
        // cannot separate them and a pattern can.
        let cosine: f64 = (0..CHANNELS).map(|i| coking[i] * misfire[i]).sum();
        assert!(cosine > 0.9, "the pair should be near-parallel: {cosine}");
    }

    /// A sensor fault has to look like a sensor fault: one channel and nothing
    /// else. That narrowness is why the posterior can reject it when the engine
    /// really has moved, and it is the row that keeps an operator from opening a
    /// healthy engine.
    #[test]
    fn a_drifting_probe_has_a_single_channel_signature() {
        let s = built();
        let row = s.row(index_of("EGT 3 SENSOR DRIFT"));
        assert!((row[ch::EGT + 2] - 1.0).abs() < 1e-12);
        for (i, v) in row.iter().enumerate() {
            if i != ch::EGT + 2 {
                assert!(v.abs() < 1e-12, "channel {i} moved");
            }
        }
    }

    /// Each fault has to be recovered from its own signature, or the matrix does
    /// not isolate anything.
    #[test]
    fn every_hypothesis_diagnoses_itself() {
        let s = built();
        for (h, entry) in CATALOGUE.iter().enumerate() {
            if h == NOMINAL {
                continue;
            }
            let observed = along(&s, h, 6.0);
            let d = s.diagnose(&observed, true);
            assert_eq!(
                d.best, h,
                "{} was diagnosed as {}",
                entry.0.name, CATALOGUE[d.best].0.name
            );
            assert!(
                (d.match_score[h] - 1.0).abs() < 1e-9,
                "{} match {}",
                entry.0.name,
                d.match_score[h]
            );
        }
    }

    /// Isolation asks which fault, never whether. Without the detection gate a
    /// healthy engine's noise is diagnosed as whichever fault it happens to lie
    /// nearest, which is the failure mode that makes a diagnosis screen useless.
    #[test]
    fn a_healthy_engine_is_nominal_and_only_because_detection_says_so() {
        let s = built();
        let noise: [f64; CHANNELS] = std::array::from_fn(|i| if i % 3 == 0 { 0.4 } else { -0.3 });

        let gated = s.diagnose(&noise, false);
        assert_eq!(gated.best, NOMINAL);
        assert!((gated.posterior[NOMINAL] - 1.0).abs() < 1e-12);

        // Ungated, the penalty still has to keep the null ahead of a fault that
        // explains nothing more than the noise does.
        let ungated = s.diagnose(&noise, true);
        assert_eq!(
            ungated.best, NOMINAL,
            "noise was diagnosed as {}",
            CATALOGUE[ungated.best].0.name
        );
    }

    /// The posterior has to be a distribution. A screen printing percentages that
    /// do not sum to a hundred is the single fastest way to lose a judge.
    #[test]
    fn the_posterior_is_a_distribution() {
        let s = built();
        for detected in [false, true] {
            let observed = along(&s, index_of("RADIATOR FOULING"), 5.0);
            let d = s.diagnose(&observed, detected);
            let total: f64 = d.posterior.iter().sum();
            assert!((total - 1.0).abs() < 1e-9, "{total}");
            assert!(d.posterior.iter().all(|p| (0.0..=1.0).contains(p)));
        }
    }

    /// A fault pushing a channel the other way is not evidence for that fault at a
    /// negative severity. An injector cannot un-coke.
    #[test]
    fn a_signature_pointing_the_wrong_way_is_not_evidence() {
        let s = built();
        let h = index_of("INJECTOR 3 COKING");
        let backwards = along(&s, h, -6.0);
        let d = s.diagnose(&backwards, true);
        assert_ne!(d.best, h);
        assert!(d.match_score[h] < -0.9, "{}", d.match_score[h]);
    }

    /// Severity must not change which fault is named. The match score is a cosine
    /// precisely so that a fault caught early is the same diagnosis as one caught
    /// late, with less confidence rather than a different answer.
    #[test]
    fn the_diagnosis_does_not_depend_on_how_far_the_fault_has_progressed() {
        let s = built();
        let h = index_of("INJECTOR 3 COKING");
        let mut previous = 0.0;
        for sigmas in [4.0, 8.0, 16.0] {
            let d = s.diagnose(&along(&s, h, sigmas), true);
            assert_eq!(d.best, h);
            assert!((d.match_score[h] - 1.0).abs() < 1e-9);
            assert!(d.posterior[h] >= previous, "confidence fell with severity");
            previous = d.posterior[h];
        }
    }

    /// The rejection has to name the channel that actually decided it, not any
    /// channel. Coking and misfire differ on **fuel flow** and nowhere else, so that
    /// is the only defensible answer and it is the one the screen quotes.
    #[test]
    fn a_rejected_hypothesis_names_the_channel_that_rejected_it() {
        let s = built();
        let coking = index_of("INJECTOR 3 COKING");
        let misfire = index_of("CYLINDER 3 MISFIRE");

        let d = s.diagnose(&along(&s, coking, 8.0), true);
        assert_eq!(d.best, coking);
        assert_eq!(d.rejection[d.best], "");
        assert_eq!(d.rejection[misfire], "FUEL");

        // And symmetrically: the same channel separates the pair either way round.
        let d = s.diagnose(&along(&s, misfire, 8.0), true);
        assert_eq!(d.best, misfire);
        assert_eq!(d.rejection[coking], "FUEL");
    }

    /// Every row needs a subsystem the health rail also knows about, so a
    /// diagnosis and the rail beside it cannot name different things.
    #[test]
    fn every_hypothesis_maps_onto_a_scored_subsystem() {
        for h in catalogue() {
            assert!(h.subsystem < crate::indices::INDICES, "{}", h.name);
        }
        assert!(catalogue().iter().filter(|h| h.instrument).count() >= 1);
    }
}
