//! Print the structured residual matrix, generated from the engine model.
//!
//! `just signatures` writes `docs/fault_signatures.md`. The document is generated
//! and never edited, for the same reason `docs/model_validation.md` is: a table of
//! fault signatures somebody typed is an assertion, and one the model produced is
//! a result. Every cell comes from running the perturbed engine to steady state.

use twin_core::channels::{CHANNELS, TABLE};
use twin_core::signature::{HYPOTHESES, NOMINAL, Signatures, catalogue};

fn main() -> std::io::Result<()> {
    let params = engine_model::engines::ae330();
    let signatures = Signatures::generate(&params);
    let rows = catalogue();

    let mut out = String::new();
    out.push_str("# Fault signature matrix\n\n");
    out.push_str(
        "Generated by `just signatures`. Do not edit: every number here comes from running\n\
         the engine model with one parameter perturbed, settling it, and differencing the\n\
         result against the healthy engine at the same operating point.\n\n",
    );
    out.push_str(&format!("Engine: {}\n\n", params.name));
    out.push_str(
        "Reference point is the canonical cruise condition, 3720 rpm at 22,400 ft on a\n\
         standard day. Each row is a **unit vector**: the direction a fault pushes the\n\
         residual, in each channel's own standard deviations, with severity divided out.\n\
         A cell is that direction's component, so a row of one large cell is a\n\
         single-channel fault and a row spread across many is not.\n\n",
    );

    out.push_str("| hypothesis |");
    for c in &TABLE {
        out.push_str(&format!(" {} |", c.name));
    }
    out.push_str("\n| --- |");
    for _ in 0..CHANNELS {
        out.push_str(" ---: |");
    }
    out.push('\n');

    for (h, row) in rows.iter().enumerate() {
        if h == NOMINAL {
            continue;
        }
        out.push_str(&format!("| {} |", row.name));
        for v in signatures.row(h) {
            if v.abs() < 0.01 {
                out.push_str(" . |");
            } else {
                out.push_str(&format!(" {v:+.2} |"));
            }
        }
        out.push('\n');
    }

    out.push_str("\n## How separable is each pair\n\n");
    out.push_str(
        "Cosine between every pair of signatures. One means the two faults are\n\
         indistinguishable from the residual pattern alone and something outside this\n\
         matrix has to separate them; zero means they are orthogonal and any observation\n\
         decides between them cleanly.\n\n",
    );
    out.push_str("| |");
    for (h, row) in rows.iter().enumerate() {
        if h != NOMINAL {
            out.push_str(&format!(" {} |", short(row.name)));
        }
    }
    out.push_str("\n| --- |");
    for _ in 1..HYPOTHESES {
        out.push_str(" ---: |");
    }
    out.push('\n');
    for (a, row) in rows.iter().enumerate() {
        if a == NOMINAL {
            continue;
        }
        out.push_str(&format!("| {} |", short(row.name)));
        for b in 0..HYPOTHESES {
            if b == NOMINAL {
                continue;
            }
            let c: f64 = signatures
                .row(a)
                .iter()
                .zip(signatures.row(b))
                .map(|(x, y)| x * y)
                .sum();
            out.push_str(&format!(" {c:+.2} |"));
        }
        out.push('\n');
    }

    std::fs::create_dir_all("docs")?;
    std::fs::write("docs/fault_signatures.md", &out)?;
    println!("{out}");
    Ok(())
}

/// An abbreviation short enough for a square matrix header.
fn short(name: &str) -> String {
    name.split_whitespace()
        .map(|w| w.chars().next().unwrap_or(' '))
        .collect()
}
