#!/usr/bin/env python3
"""Emit DroneCAN v0 reference frames for the dronecan-ice golden-vector tests.

Encodes a fixed set of field values with pydronecan, the reference implementation,
and prints them as a Rust source file. Run once when the message set changes:

    just golden

Python is never in the runtime path; this produces committed test fixtures only.
"""

import sys
import dronecan
from dronecan import uavcan
from dronecan.transport import Transfer

NODE_ID = 42
PRIORITY = 16


def frames(msg, transfer_id):
    t = Transfer(
        payload=msg,
        source_node_id=NODE_ID,
        transfer_id=transfer_id,
        transfer_priority=PRIORITY,
    )
    return [(f.message_id, bytes(f.bytes)) for f in t.to_frames()]


def reciprocating_status():
    m = uavcan.equipment.ice.reciprocating.Status()
    m.state = 2  # STATE_RUNNING
    m.flags = 8 | 32768  # TEMPERATURE_SUPPORTED | OIL_PRESSURE_SUPPORTED
    m.engine_load_percent = 34
    m.engine_speed_rpm = 3720
    m.spark_dwell_time_ms = float("nan")
    m.atmospheric_pressure_kpa = 42.07
    m.intake_manifold_pressure_kpa = 118.0
    m.intake_manifold_temperature = 318.5
    m.coolant_temperature = 361.0
    m.oil_pressure = 420.0
    m.oil_temperature = 358.0
    m.fuel_pressure = 180000.0
    m.fuel_consumption_rate_cm3pm = 255.0
    m.estimated_consumed_fuel_volume_cm3 = 65500.0
    m.throttle_position_percent = 34
    m.ecu_index = 0
    m.spark_plug_usage = 0
    for i, (cht, egt, lam) in enumerate(
        [(412.0, 843.0, 1.68), (408.0, 839.0, 1.71), (419.0, 887.0, 1.89), (406.0, 841.0, 1.70)]
    ):
        c = uavcan.equipment.ice.reciprocating.CylinderStatus()
        c.ignition_timing_deg = float("nan")
        c.injection_time_ms = 1.5 + 0.125 * i
        c.cylinder_head_temperature = cht
        c.exhaust_gas_temperature = egt
        c.lambda_coefficient = lam
        m.cylinder_status.append(c)
    return m


def fuel_tank_status():
    m = uavcan.equipment.ice.FuelTankStatus()
    m.available_fuel_volume_percent = 63
    m.available_fuel_volume_cm3 = 189000.0
    m.fuel_consumption_rate_cm3pm = 255.0
    m.fuel_temperature = 291.0
    m.fuel_tank_id = 0
    return m


def static_pressure():
    m = uavcan.equipment.air_data.StaticPressure()
    m.static_pressure = 42070.0
    m.static_pressure_variance = 4.0
    return m


def static_temperature():
    m = uavcan.equipment.air_data.StaticTemperature()
    m.static_temperature = 242.15
    m.static_temperature_variance = 0.25
    return m


def indicated_airspeed():
    m = uavcan.equipment.air_data.IndicatedAirspeed()
    m.indicated_airspeed = 40.125
    m.indicated_airspeed_variance = 0.5
    return m


def circuit_status():
    m = uavcan.equipment.power.CircuitStatus()
    m.circuit_id = 1
    m.voltage = 27.8
    m.current = 42.0
    m.error_flags = 0
    return m


CASES = [
    ("RECIPROCATING_STATUS", reciprocating_status, 7),
    ("FUEL_TANK_STATUS", fuel_tank_status, 3),
    ("STATIC_PRESSURE", static_pressure, 1),
    ("STATIC_TEMPERATURE", static_temperature, 2),
    ("INDICATED_AIRSPEED", indicated_airspeed, 5),
    ("CIRCUIT_STATUS", circuit_status, 9),
]


def main():
    out = []
    out.append("// Generated by scripts/golden_vectors.py against pydronecan %s." % dronecan.__version__)
    out.append("// Do not edit by hand: regenerate with `just golden`.")
    out.append("//")
    out.append("// Each entry is one CAN frame of one transfer, in transmission order,")
    out.append("// as the reference implementation emits it for the field values the")
    out.append("// generator script sets. Source node %d, priority %d." % (NODE_ID, PRIORITY))
    out.append("")
    out.append("/// Source node ID the vectors were generated with.")
    out.append("pub const NODE_ID: u8 = %d;" % NODE_ID)
    out.append("/// Transfer priority the vectors were generated with.")
    out.append("pub const PRIORITY: u8 = %d;" % PRIORITY)
    for name, build, tid in CASES:
        fs = frames(build(), tid)
        out.append("")
        out.append("/// Transfer ID used for the `%s` vector." % name)
        out.append("pub const %s_TRANSFER_ID: u8 = %d;" % (name, tid))
        out.append("/// `(can_id, frame_data)` for every frame of the `%s` transfer." % name)
        out.append("pub const %s: &[(u32, &[u8])] = &[" % name)
        for cid, data in fs:
            body = ", ".join("0x%02x" % b for b in data)
            out.append("    (0x%08x, &[%s])," % (cid, body))
        out.append("];")
        print("%-22s %2d frame(s)  id=0x%08x" % (name, len(fs), fs[0][0]), file=sys.stderr)
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
