[package]
name = "twin-core"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
engine-model.workspace = true
nalgebra = "0.35.0"
rustfft = "6.4.1"
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
dragonfly-sim.workspace = true
