// Generated by scripts/golden_vectors.py against pydronecan 1.0.27.
// Do not edit by hand: regenerate with `just golden`.
//
// Each entry is one CAN frame of one transfer, in transmission order,
// as the reference implementation emits it for the field values the
// generator script sets. Source node 42, priority 16.

/// Source node ID the vectors were generated with.
pub const NODE_ID: u8 = 42;
/// Transfer priority the vectors were generated with.
pub const PRIORITY: u8 = 16;

/// Transfer ID used for the `RECIPROCATING_STATUS` vector.
pub const RECIPROCATING_STATUS_TRANSFER_ID: u8 = 7;
/// `(can_id, frame_data)` for every frame of the `RECIPROCATING_STATUS` transfer.
pub const RECIPROCATING_STATUS: &[(u32, &[u8])] = &[
    (
        0x1004602a,
        &[0x41, 0x99, 0x82, 0x20, 0x00, 0x00, 0x00, 0x87],
    ),
    (
        0x1004602a,
        &[0x00, 0x45, 0x10, 0x1c, 0xff, 0x7f, 0x42, 0x27],
    ),
    (
        0x1004602a,
        &[0x51, 0x60, 0x57, 0xfa, 0x5c, 0xa4, 0x5d, 0x07],
    ),
    (
        0x1004602a,
        &[0x90, 0x5e, 0x98, 0x5d, 0xff, 0x7b, 0x00, 0x27],
    ),
    (
        0x1004602a,
        &[0x00, 0x7f, 0x43, 0x00, 0xdc, 0x7f, 0x47, 0x07],
    ),
    (
        0x1004602a,
        &[0x44, 0x00, 0xff, 0x7f, 0x00, 0x3e, 0x70, 0x27],
    ),
    (
        0x1004602a,
        &[0x5e, 0x96, 0x62, 0xb8, 0x3e, 0xff, 0x7f, 0x07],
    ),
    (
        0x1004602a,
        &[0x80, 0x3e, 0x60, 0x5e, 0x8e, 0x62, 0xd7, 0x27],
    ),
    (
        0x1004602a,
        &[0x3e, 0xff, 0x7f, 0x00, 0x3f, 0x8c, 0x5e, 0x07],
    ),
    (
        0x1004602a,
        &[0xee, 0x62, 0x8f, 0x3f, 0xff, 0x7f, 0x80, 0x27],
    ),
    (
        0x1004602a,
        &[0x3f, 0x58, 0x5e, 0x92, 0x62, 0xcd, 0x3e, 0x47],
    ),
];

/// Transfer ID used for the `FUEL_TANK_STATUS` vector.
pub const FUEL_TANK_STATUS_TRANSFER_ID: u8 = 3;
/// `(can_id, frame_data)` for every frame of the `FUEL_TANK_STATUS` transfer.
pub const FUEL_TANK_STATUS: &[(u32, &[u8])] = &[
    (
        0x1004692a,
        &[0x02, 0x68, 0x00, 0x3f, 0x00, 0x92, 0x38, 0x83],
    ),
    (
        0x1004692a,
        &[0x48, 0x00, 0x00, 0x7f, 0x43, 0x8c, 0x5c, 0x23],
    ),
    (0x1004692a, &[0x00, 0x43]),
];

/// Transfer ID used for the `STATIC_PRESSURE` vector.
pub const STATIC_PRESSURE_TRANSFER_ID: u8 = 1;
/// `(can_id, frame_data)` for every frame of the `STATIC_PRESSURE` transfer.
pub const STATIC_PRESSURE: &[(u32, &[u8])] =
    &[(0x1004042a, &[0x00, 0x56, 0x24, 0x47, 0x00, 0x44, 0xc1])];

/// Transfer ID used for the `STATIC_TEMPERATURE` vector.
pub const STATIC_TEMPERATURE_TRANSFER_ID: u8 = 2;
/// `(can_id, frame_data)` for every frame of the `STATIC_TEMPERATURE` transfer.
pub const STATIC_TEMPERATURE: &[(u32, &[u8])] = &[(0x1004052a, &[0x91, 0x5b, 0x00, 0x34, 0xc2])];

/// Transfer ID used for the `INDICATED_AIRSPEED` vector.
pub const INDICATED_AIRSPEED_TRANSFER_ID: u8 = 5;
/// `(can_id, frame_data)` for every frame of the `INDICATED_AIRSPEED` transfer.
pub const INDICATED_AIRSPEED: &[(u32, &[u8])] = &[(0x1003fd2a, &[0x04, 0x51, 0x00, 0x38, 0xc5])];

/// Transfer ID used for the `CIRCUIT_STATUS` vector.
pub const CIRCUIT_STATUS_TRANSFER_ID: u8 = 9;
/// `(can_id, frame_data)` for every frame of the `CIRCUIT_STATUS` transfer.
pub const CIRCUIT_STATUS: &[(u32, &[u8])] = &[(
    0x1004432a,
    &[0x01, 0x00, 0xf3, 0x4e, 0x40, 0x51, 0x00, 0xc9],
)];
